---
- name: install tmpreaper
  apt: pkg=tmpreaper state=installed
  tags:
     - install_tmpreaper

- name: setup config
  copy: src=tmpreaper.conf dest=/etc/tmpreaper.conf
  tags:
     - configure_tmpreaper
