---
hosted: aws
users_extra:
  - name: 'pudo'
    groups:
      - openspending_dev
    authorized_keys:
      - 'pudo'
  - name: 'stiivi'
    groups:
      - openspending_dev
    authorized_keys:
      - 'stiivi'
sudo_extras:
  - tryggvib
  - dfowler
sudo_extra_lines:
  - '%openspending_dev ALL=(ALL) NOPASSWD: /usr/bin/supervisorctl *'
sites_to_monitor:
  - farmsubsidy.openspending.org:80:200
  - openspending.org:80:301
ssl_sites_to_monitor:
  - openspending.org
