#Adds scripts, which can be defined per host/group basis, these variables which accept a list,
#
# scripts: generic scripts
# enabled_local_checks: list of check_mk local checks which should be enabled - http://mathias-kettner.de/checkmk_localchecks.html
# disabled_local_checks: local checks that should be disabled

---
- name: ensure_directory
  file: state=directory dest={{ item }} owner=root group=root
  with_items:
     - /opt/scripts
  tags: scripts

- name: ensure_scripts
  copy: src=opt/scripts/{{ item }} dest=/opt/scripts/
  with_items: scripts
  when: scripts is defined
  tags: scripts

- name: install pip
  apt: pkg=python-pip state=installed update_cache=yes
  tags: scripts

- name: ensure_configparser
  pip: name=configparser
  tags: scripts

## tasks for check_mk check scripts
- name: setup_local_checks_dir
  file: path={{ item }} state=directory
  when: enabled_local_checks is defined
  with_items:
     - '/opt/scripts/check_mk'
     - '/usr/lib/check_mk_agent/local/86400'
  tags:
     - scripts
     - local_checks

- name: setup_local_checks
  copy: src=opt/scripts/check_mk/{{ item }} dest=/opt/scripts/check_mk/ mode=0744
  with_items: enabled_local_checks
  when: enabled_local_checks is defined
  tags:
     - scripts
     - local_checks

- name: setup_local_checks
  file: src=/opt/scripts/check_mk/{{ item }} dest={{ local_checks_path }}/{{ item }} state=link force=yes
  with_items: enabled_local_checks
  when: enabled_local_checks is defined
  tags:
     - scripts
     - local_checks

#these are checks that should run once every 600 secs, see http://mathias-kettner.de/checkmk_localchecks.html
- name: setup_local_checks
  copy: src=opt/scripts/check_mk/{{ item }} dest=/opt/scripts/check_mk/
  with_items: enabled_local_checks_86400
  when: enabled_local_checks_86400 is defined
  tags:
     - scripts
     - local_checks

- name: setup_local_checks_86400
  file: src=/opt/scripts/check_mk/{{ item }} dest=/usr/lib/check_mk_agent/local/86400/{{ item }} state=link force=yes
  with_items: enabled_local_checks_86400
  when: enabled_local_checks_86400 is defined
  tags:
     - scripts
     - local_checks

# this removes a check if the disabled_checks array is defined, and has names of checks to be disabled
- name: disable_local_checks
  file: src={{ local_checks_path }}/{{ item }} state=absent
  with_items: disabled_local_checks
  when: disabled_local_checks is defined
  tags:
     - scripts
     - local_checks
     - disable_checks

- name: disable_checks
  file: path=/opt/scripts/check_mk/{{ item }} state=absent
  with_items: disabled_local_checks
  when: disabled_local_checks is defined
  tags:
     - scripts
     - local_checks
     - disable_checks

# this adds custom nagios checks
- name: create folder for custom nagios checks
  file: path=/opt/scripts/nagios_checks state=directory
  when: enabled_nagios_checks is defined
  tags:
     - scripts
     - nagios_check_scripts

- name: enable_nagios_checks
  copy: src=opt/scripts/nagios_checks/{{ item }} dest=/opt/scripts/nagios_checks/{{ item }} mode=0655
  with_items: enabled_nagios_checks
  when: enabled_nagios_checks is defined
  tags:
     - scripts
     - nagios_check_scripts

- name: disable_nagios_checks
  file: path=/opt/scripts/nagios_checks/{{ item }} state=absent
  with_items: disabled_nagios_checks
  when: disabled_nagios_checks is defined
  tags:
     - scripts
     - local_checks
     - disable_nagios_checks

- name: copy postfix related scripts
  copy: src={{ item }} dest=/opt/scripts/ owner=root mode=0655
  with_fileglob:
     - opt/scripts/mail/*
  when: mail_scripts is defined
  tags:
     - scripts
     - mail_scripts

- name: copy mail cronjobs
  copy: src=opt/scripts/mail/cron.d/mailman_weekly_stats dest=/etc/cron.d/mailman_weekly_stats group=root owner=root mode=655
  when: mail_scripts is defined
  tags:
     - scripts
     - mail_scripts
