#Adds scripts, which can be defined per host/group basis, these variables which accept a list,
#
# scripts: generic scripts
# graphite_collectors : list of  graphite collector script names to be included
#
# The script sets up /opt/scripts/config/config.cfg which is required by some scripts.
---
- name: ensure_directory
  file: state=directory dest={{ item }} owner=root group=root
  with_items:
     - /opt/scripts
     - /opt/scripts/config
  tags: scripts

- name: ensure_scripts
  copy: src=opt/scripts/{{ item }} dest=/opt/scripts/
  with_items: scripts
  when: scripts is defined
  tags: scripts

- name: install pip
  apt: pkg=python-pip state=installed update_cache=yes
  tags: scripts

- name: ensure_configparser
  pip: name=configparser
  tags: scripts

#some script config might be private
- name: ensure_script_config
  template: src={{ item }} dest=/opt/scripts/config/config.ini
  with_first_found:
     - files:
        - opt/scripts/config/{{ inventory_hostname }}/config.j2
        - opt/scripts/config/config.j2
       paths:
        - ../templates
  ignore_errors: true
  tags: scripts

## tasks for graphite collector scripts
- name: ensure_graphite_scripts_dir
  file: path={{ item }} state=directory
  when: graphite_collectors is defined
  with_items:
     - '/opt/scripts/graphite_collectors'
     - '/opt/scripts/graphite_collectors/myutils'
  tags:
     - scripts
     - graphite_collectors

- name: add_myutils
  copy: src={{ item }} dest=/opt/scripts/graphite_collectors/myutils/
  with_fileglob:
     - opt/scripts/graphite_collectors/myutils/*
  when: graphite_collectors is defined
  tags:
     - scripts
     - graphite_utils
     - graphite_collectors

- name: ensure_collectors
  copy: src=opt/scripts/graphite_collectors/{{ item }} dest=/opt/scripts/graphite_collectors/
  with_items: graphite_collectors
  when: graphite_collectors is defined
  tags:
     - scripts
     - graphite_collectors

- name: ensure_collector_cronjobs
  copy: src=opt/scripts/graphite_collectors/cron.d/{{ item.split('.')[0] }}_graphite dest=/etc/cron.d/ owner=root group=root
  with_items: graphite_collectors
  when: graphite_collectors is defined
  tags:
     - scripts
     - graphite_collectors

# this adds custom nagios checks
- name: create folder for custom nagios checks
  file: path=/opt/scripts/nagios_checks state=directory
  when: enabled_nagios_checks is defined
  tags:
     - scripts
     - nagios_check_scripts

- name: enable_nagios_checks
  copy: src=opt/scripts/nagios_checks/{{ item }} dest=/opt/scripts/nagios_checks/{{ item }} mode=0655
  with_items: enabled_nagios_checks
  when: enabled_nagios_checks is defined
  tags:
     - scripts
     - nagios_check_scripts

- name: disable_nagios_checks
  file: path=/opt/scripts/nagios_checks/{{ item }} state=absent
  with_items: disabled_nagios_checks
  when: disabled_nagios_checks is defined
  tags:
     - scripts
     - local_checks
     - disable_nagios_checks

- name: copy postfix related scripts
  copy: src={{ item }} dest=/opt/scripts/ owner=root mode=0655
  with_fileglob:
     - opt/scripts/mail/*
  when: mail_scripts is defined
  tags:
     - scripts
     - mail_scripts

- name: copy mail cronjobs
  copy: src=opt/scripts/mail/cron.d/mailman_weekly_stats dest=/etc/cron.d/mailman_weekly_stats group=root owner=root mode=655
  when: mail_scripts is defined
  tags:
     - scripts
     - mail_scripts
