- name: install okfn-heroku-copyapp script
  copy: src=copyapp
        dest=/usr/local/bin/okfn-heroku-copyapp
        owner=root
        group=root
        mode=0755

- name: install cronjob
  cron: name="copy okfn.org production data to staging"
        user=heroku
        hour=2
        minute=30
        job="PATH=/usr/local/bin:$PATH QUIET=1 /usr/local/bin/okfn-heroku-copyapp okfn-production okfn-staging && curl https://nosnch.in/{{ okfn_org_manager_snitch_id }} >/dev/null 2>&1"
        state=present
