---
- include_vars: "{{ private_dir }}/p.yml"

# We set install_recommends to no here, and install php5 explicitly, to ensure
# that installing nagios doesn't automatically pull in Apache.
- name: install nagios3
  apt: pkg='{{ item }}'
       install_recommends=no
       state=present
  with_items:
    - php5
    - fcgiwrap
    - nagios3
  notify: setuid nagios plugins

- name: setup symlinks for nagios cgi
  file: src='{{ item.src }}' dest='{{ item.dest }}' state=link
  with_items:
    - src: /etc/nagios3/stylesheets
      dest: /usr/share/nagios3/htdocs/stylesheets
    - src: /usr/share/nagios3/htdocs/
      dest: /usr/share/nagios3/htdocs/nagios3

- name: add private key for check_by_ssh checks
  copy: src='{{ private_dir }}/nagios_id_rsa.private'
        dest=/home/nagios/.ssh/id_rsa
        owner=nagios
        group=nagios
        mode=600

- name: setup ssh config to disable strict host checking
  copy: src=ssh_config
        dest=/home/nagios/.ssh/config
        owner=nagios
        group=nagios
        mode=600

- name: nagios_config
  copy: src='{{ item }}' dest=/etc/nagios3/
  notify: reload nagios
  with_fileglob:
    - etc/nagios3/*

- name: nagios_config_confd
  copy: src='{{ item }}'
        dest=/etc/nagios3/conf.d/
        owner=root
        group=nagios
        mode=0664
  notify: reload nagios
  with_fileglob:
    - etc/nagios3/conf.d/*

- name: install deps for pagerduty plugin
  apt: pkg='{{ item }}' state=present
  with_items:
  - libwww-perl
  - libcrypt-ssleay-perl

- name: install custom nagios plugins
  copy: src='usr/local/bin/{{ item }}'
        dest='/usr/local/bin/{{ item }}'
        mode=775
        owner=root
        group=nagios
  notify: reload nagios
  with_items:
    - pagerduty_nagios.pl

- name: install pagerduty config
  template: src=etc/nagios3/conf.d/pagerduty_nagios.cfg.j2
            dest=/etc/nagios3/conf.d/pagerduty_nagios.cfg
            owner=root
            group=nagios
            mode=0664
  notify: reload nagios

- name: install pagerduty cronjob
  copy: src=etc/cron.d/pagerduty_nagios
        dest=/etc/cron.d/pagerduty_nagios
        owner=root
        group=nagios
        mode=775

