---
 - name: check if omeka is installed
   stat: path=/var/www/omeka/.installed
   register: omeka_exists

 - name: Get the omeka source code
   get_url: url=http://omeka.org/files/omeka-2.2.2.zip dest=/tmp
   when: omeka_exists.stat.exists == false

 - name: Unzip the source code
   unarchive: src=/tmp/omeka-2.2.2.zip dest=/tmp copy=no creates=no
   when: omeka_exists.stat.exists == false

 - name: Create /var/www
   file: path=/var/www state=directory
   when: omeka_exists.stat.exists == false

 - name: Move omeka code into /var/www/omeka
   command: mv /tmp/omeka-2.2.2/ /var/www/omeka/
   when: omeka_exists.stat.exists == false

 - name: Copy config file over to Omeka
   template: src=db.ini.j2 dest=/var/www/omeka/db.ini owner=www-data group=www-data mode=0644
   when: omeka_exists.stat.exists == false

# The database is already setup in RDS, so no work needs to be done on the DB.

 - name: Clone okfn omeka plugin repo
   git: repo=https://github.com/okfn/infra-omeka.git
        dest=/opt/infra-omeka
        update=yes
        accept_hostkey=yes

 - name: Clone okfn omeka theme repo
   git: repo=https://github.com/okfn/omeka-theme-glam.git
        dest=/opt/omeka-theme-glam
        update=yes
        accept_hostkey=yes

 - name: Symlink plugins from repo into plugin directory
   file: src=/opt/infra-omeka/plugins/{{ item }}
         dest=/var/www/omeka/plugins/{{ item }}
         state=link
   with_items:
     - GuestUser
     - Geolocation
     - EmbedCodes
     - Contribution
     - DerivativeImages
     - Commenting
     - CsvImport
     - DigitalObjectLinker
     - SearchByMetadata
     - RecordRelations
     - UserProfiles
     - SocialBookmarking
   tags:
     - omeka_symlink_plugins

 - name: Symlink theme from repo into theme directory
   file: src=/opt/omeka-theme-glam
         dest=/var/www/omeka/themes/omeka-theme-glam
         state=link

 - name: Set the permissions on the Omeka directory
   file: path=/var/www/omeka/files owner=www-data group=www-data recurse=yes
   when: omeka_exists.stat.exists == false

 - name: Set the permissions on the Omeka csv-plugin directory
   file: path=/var/www/omeka/plugins/CsvImport/csv_files owner=www-data group=www-data recurse=yes
   when: omeka_exists.stat.exists == false

 - name: Set the permissions on the Omeka contribution plugin
   file: path=/var/www/omeka/plugins/Contribution/upgrade_files
   when: omeka_exists.stat.exists == false

 - name: Set the permissions on the Omeka applications logs directory
   file: path=/var/www/omeka/application/logs owner=www-data group=www-data recurse=yes
   when: omeka_exists.stat.exists == false

 - name: Create installed file in /var/www/omeka
   file: path=/var/www/omeka/.installed owner=www-data group=www-data mode=0644 state=touch
   when: omeka_exists.stat.exists == false
