---
users:
  rgrp:
    name: 'rgrp'
    authorized_keys:
      - rgrp
  okfn:
    name: 'okfn'
    authorized_keys:
      - okfn
  nigelb:
    name: 'okfn'
    authorized_keys:
      - nigelb
  matt:
    name: 'matt'
    authorized_keys:
      - matt
  amercader:
    name: 'matt'
    authorized_keys:
      - amercader
  joetsoi:
    name: 'joetsoi'
    authorized_keys:
      - joetsoi
  vitor:
    name: 'vitor'
    authorized_keys:
      - vitor
  tryggvib:
    name: 'tryggvib'
    authorized_keys:
      - tryggvib
  brook:
    name: 'brook'
    authorized_keys:
      - brook
  stefan:
    name: 'stefan'
    authorized_keys:
      - stefan
  holger:
    name: 'holger'
    authorized_keys:
      - holger
  rowan:
    name: 'rowan.crawford'
    authorized_keys:
      - rowan.crawford
  joost:
    name: 'joost.cassee'
    authorized_keys:
      - joost.cassee
  yohan.boniface:
    name: 'yohan.boniface'
    authorized_keys:
      - yohan.boniface
  ross:
    name: 'ross.jones'
    authorized_keys:
      - ross.jones
  pudo:
    name: 'pudo'
    authorized_keys:
      - pudo
  pierre.yves:
    name: 'pierre.yves'
    authorized_keys:
      - pierre.yves
  umbrich:
    name: 'umbrich'
    authorized_keys:
      - umbrich
  tonyh:
    name: 'tonyh'
    authorized_keys:
      - tonyh
  nagios:
    name: 'nagios'
    authorized_keys:
      - nagios
  dfowler:
    name: 'dfowler'
    authorized_keys:
      - dfowler
  caleb:
    name: 'caleb'
    authorized_keys:
      - caleb
