#ansible-playbook main.yml --tags="base-roles" -vvv
---
- hosts: all
  sudo: true
  vars:
     - private_dir: ../../credentials/ansible
  vars_files:
    - vars/users.yml
    - vars/groups.yml
    - "{{ private_dir }}/p.yml"
  roles:
    - { role: check-mk-agent, tags: ['check-mk-agent'] }
    - { role: cron, tags: ['cron'] }
    - { role: iptables-persistent, tags: ['iptables-persistent'] }
    - { role: motd, tags: ['motd'] }
    - { role: nagios-client, tags: ['nagios-client'] }
    - postfix
    - { role: knopki.timezone, tags: ['time'] }
    - { role: bennojoy.ntp, tags: ['time'] }
    - { role: update-notifier, tags: ['update-notifier'] }
    - { role: users, group: 'sysadmin', tags: ['users'] }
    - { role: sudo , tags: ['sudo'] }
    - { role: db-backup, tags: ['db-backup'] }
    - { role: apt-mirror-config, tags: ['apt-mirror-config'] }
    - { role: unattended-upgrades, tags: ['unattended-upgrades'] }
    - { role: apt, tags: ['git'], pkg_list: ['git'] }
    - { role: apt, tags: ['sysstat'], pkg_list: ['sysstat'] }
    - { role: sshd, tags: ['sshd'] }
    - { role: fail2ban, tags: ['fail2ban'] }

- hosts: omeka
  sudo: true
  vars:
     - private_dir: ../../credentials/ansible
  vars_files:
    - "{{ private_dir }}/p.yml"
  roles:
    - { role: apt, tags: ['unzip'], pkg_list: ['unzip', 'php5-fpm', 'php5-mysql'] }
    - { role: apt, tags: ['imagemagick'], pkg_list: ['imagemagick', 'php5-imagick'] }
    - { role: omeka, tags: ['omeka-opencollections'], install_dir: '/var/www/omeka', omeka_db_password: "{{ omeka[0].db_password }}", omeka_db_name: 'omeka' }
    - { role: omeka, tags: ['omeka-espace'], install_dir: '/var/www/espace-omeka',
omeka_db_password: "{{ omeka[1].db_password }}", omeka_db_name: 'espace_omeka' }
    - { role: nginx, tags: ['nginx'] }

- hosts: rt
  sudo: true
  vars:
     - private_dir: ../../credentials/ansible
  vars_files:
    - "{{ private_dir }}/p.yml"
  roles:
    - { role: rt, tags: ['rt'] }
    - { role: postfix, tags: ['postfix'] }
    - { role: nginx, tags: ['nginx'] }
    - { role: supervisor, tags: ['supervisor'] }


- hosts: openspending-solr
  sudo: true
  roles:
    - { role: apt, tags: ['python'], pkg_list: ['python-setuptools', 'python-virtualenv'] }
    - { role: supervisor, tags: ['supervisor'] }

- hosts: openspending-web
  sudo: true
  vars:
     - private_dir: ../../credentials/ansible
  vars_files:
    - "{{ private_dir }}/p.yml"
  roles:
    - { role: nginx, tags: ['nginx'] }

- hosts: s133.okserver.org
  sudo: true
  vars:
     - private_dir: ../../credentials/ansible
  vars_files:
    - "{{ private_dir }}/p.yml"
  roles:
    - role: varnish
      tags: ['varnish']
      secret: "{{ varnish_secret[0].secret }}"

- hosts: s134.okserver.org
  sudo: true
  vars:
     - private_dir: ../../credentials/ansible
  vars_files:
    - "{{ private_dir }}/p.yml"
  roles:
    - role: awscli
      tags: ['awscli']
      key: "{{ aws_keys[2].key }}"
      secret_key: "{{ aws_keys[2].secret_key }}"
      region: "{{ aws_keys[2].region }}"
      awscli_user: heroku
      awscli_group: heroku
      awscli_user_home: /home/heroku
    - { role: okfn-org-manager, tags: ['heroku-backup'] }

- hosts: s138.okserver.org
  sudo: true
  vars:
     - private_dir: ../../credentials/ansible
  vars_files:
    - "{{ private_dir }}/p.yml"
  roles:
    - role: awscli
      tags: ['awscli']
      key: "{{ aws_keys[0].key }}"
      secret_key: "{{ aws_keys[0].secret_key }}"
      region: "{{ aws_keys[0].region }}"
      awscli_user: root
      awscli_group: root
      awscli_user_home: /root

- hosts: s079.okserver.org
  sudo: true
  roles:
    - { role: nginx, tags: ['nginx'] }

- hosts: backup
  gather_facts: True
  sudo: true
  roles:
    - role: rsnapshot
      tags: ['rsnapshot']
      snapshot_root: /home/backup/snapshots/
      cmd_rsync: /usr/bin/rsync
    - role: rsyncd

- hosts: wiki
  gather_facts: false
  sudo: true
  roles:
    - { role: nginx, tags: ['nginx'] }
    - { role: php-fpm, tags: ['php-fpm'] }

- hosts: monitoring
  sudo: true
  vars:
     - private_dir: ../../credentials/ansible
  vars_files:
    - "{{ private_dir }}/p.yml"
  roles:
    - { role: nagios-server, tags: ['nagios-server'] }
    - { role: check-mk-server, tags: ['check-mk-server'] }
    - { role: nginx, tags: ['nginx'] }

- hosts: listserv
  sudo: true
  vars:
     - private_dir: ../../credentials/ansible
  vars_files:
    - "{{ private_dir }}/p.yml"
  roles:
    # Keep nginx before mailman, as mailman will want to install some config
    # files into /etc/nginx.
    - { role: nginx, tags: ['nginx'] }
    - { role: mailman, tags: ['mailman'] }

- hosts: docker-host
  sudo: true
  vars:
     - private_dir: ../../credentials/ansible
  vars_files:
    - "{{ private_dir }}/p.yml"
  roles:
    - { role: docker, tags: ['docker'] }
    - { role: nginx, tags: ['nginx'] }
    - { role: postgrey }
    - { role: postfix }

