#ansible-playbook --extra-vars="host=s999.okserver.org fact_path='/etc/ansible/facts.d'" updates.yml -vvv
---
- hosts: "{{ host }}"
  gather_facts: True
  connection: ssh
  user: okfn
  sudo: true

  tasks:
     - name: ensure facts directory
       file: dest={{ fact_path }} state=directory
       tags: ensure_facts_directory

     - name: ensure_facts_cron
       copy: src=files/cron.hourly/populate_ansible_facts.py dest=/etc/cron.hourly/populate_ansible_facts.py mode=744
       tags: ensure_facts_cron

     - name: run_facts_script
       shell: /etc/cron.hourly/populate_ansible_facts.py
       tags: run_facts_script
